name: "Conventional Commit - Action"
description: "Check the semantics used in push and pull requests."
branding:
  icon: "git-commit"
  color: "green"
inputs:
  pr-title-regex:
    description: "You can override the regex that is used to match PR title "
    required: false
    default: "^(.+)(?:(([^)s]+)))?: (.+)"
  pr-body-regex:
    description: "You can override the regex that is used to match PR body "
    required: false
    default: '(.*\n)+(.*)'
runs:
  using: "node12"
  main: "dist/index.js"
